name: video-caption

on:
  push:
    branches:
      - master

jobs:
  run:
    name: run
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Show IP
        run: |
          curl https://httpbin.org/ip
      - name: Install dependencies
        run: |
          brew update
          brew install ffmpeg
          brew install imagemagick
          brew reinstall python
          pip3 install virtualenv
      - name: Run
        env:
          BILIBILI_USERNAME: ${{ secrets.BILIBILI_USERNAME }}
          BILIBILI_PASSWORD: ${{ secrets.BILIBILI_PASSWORD }}
          GOOGLE_EMAIL_USERNAME: ${{ secrets.GOOGLE_EMAIL_USERNAME }}
          GOOGLE_EMAIL_PASSWORD: ${{ secrets.GOOGLE_EMAIL_PASSWORD }}
          GOOGLE_NOTIFIED_EMAIL: ${{ secrets.GOOGLE_NOTIFIED_EMAIL }}
        run: |
          virtualenv --python=python3 env
          source env/bin/activate
          pip install -r requirements.txt
          python main.py


